### ISSUE TITLE
Cannot use instructor with `o1-preview`

### ISSUE THREAD

**Issue by threewisemonkeys-as** [jxnl/instructor#1039]
- [X] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [X] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [X] Other (please specify)

Model: `o1-preview`

**Describe the bug**

When using instructor with `o1-preview` I run into an error -

```python

import instructor
from pydantic import BaseModel
from openai import OpenAI


# Define your desired output structure
class UserInfo(BaseModel):
    name: str
    age: int


# Patch the OpenAI client
client = instructor.from_openai(OpenAI())

# Extract structured data from natural language
user_info = client.chat.completions.create(
    model="o1-preview",
    response_model=UserInfo,
    messages=[{"role": "user", "content": "John Doe is 30 years old."}],
)

print(user_info.name)
#> John Doe
print(user_info.age)
#> 30
```

Results in - 

```
Traceback (most recent call last):
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/instructor/retry.py", line 185, in retry_sync
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 742, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/openai/_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/openai/_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/openai/_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Unsupported parameter: 'tools' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'tools', 'code': 'unsupported_parameter'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/instructor/retry.py", line 182, in retry_sync
    for attempt in max_retries:
                   ^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x11040bec0 state=finished raised BadRequestError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ays57/Documents/Projects/RubberDuckVerification/t.py", line 51, in <module>
    user_info = client.chat.completions.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/instructor/client.py", line 119, in create
    return self.create_fn(
           ^^^^^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/instructor/patch.py", line 291, in new_create_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "/Users/ays57/miniconda3/envs/rdv/lib/python3.12/site-packages/instructor/retry.py", line 220, in retry_sync
    raise InstructorRetryException(
instructor.exceptions.InstructorRetryException: Error code: 400 - {'error': {'message': "Unsupported parameter: 'tools' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'tools', 'code': 'unsupported_parameter'}}
```

It looks like `instructor` is trying to call the opeani API for o1-preview with function calling when this is not supported.
I am observing similar behavior when using `litellm` with `instructor` for `o1-preview`.

**Comment by ivanleomk** [comment]
Hi @threewisemonkeys-as , can you try this instead?

```
client = instructor.from_openai(OpenAI(), mode=instructor.Mode.JSON_O1)
```

O1 is a bit funky in the sense that it doesn't have tool calling, streaming or even support for a system prompt so i'd recommend sticking to JSON_O1 for now. 

I tested it out and the code below works. Going to close this issue for now.

```
import instructor
from pydantic import BaseModel
from openai import OpenAI


# Define your desired output structure
class UserInfo(BaseModel):
    name: str
    age: int


# Patch the OpenAI client
client = instructor.from_openai(OpenAI(), mode=instructor.Mode.JSON_O1)

# Extract structured data from natural language
user_info = client.chat.completions.create(
    model="o1-preview",
    response_model=UserInfo,
    messages=[{"role": "user", "content": "John Doe is 30 years old."}],
)

print(user_info.name)
# > John Doe
print(user_info.age)
# > 30

```

**Comment by threewisemonkeys-as** [comment]
Thanks for the speedy response!

Have you thought of modifying the behavior of instructor to use `JSON_O1` by default if `model='o1-preview'` by default?
