### ISSUE TITLE
Get wrong answer with `llm_validator`

### ISSUE THREAD

**Issue by majiayu000** [jxnl/instructor#306]
I am learning formatting resp of openai. When run the code in this page: https://jxnl.github.io/instructor/examples/self_critique/

I cant run correctly.

This is my code:
```
from instructor import llm_validator


openai_client = instructor.patch(OpenAI())

class QuestionAnswerNoEvil(BaseModel):
    question: str
    answer: Annotated[
        str,
        BeforeValidator(
            llm_validator("don't say objectionable things", allow_override=True, openai_client= openai_client)
        ),
    ]
```

I added `openai_client = instructor.patch(OpenAI())` myself to aovid `'NoneType' object has no attribute 'chat'`.

But finally got:
```
Retrying, exception: 1 validation error for QuestionAnswerNoEvil
answer
  Assertion failed, The statement promotes sin and debauchery, which can be considered objectionable. [type=assertion_error, input_value='According to the devil, ... of sin and debauchery.', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/assertion_error
Traceback (most recent call last):
  File "c:\Users\18353\AppData\Local\Programs\Python\Python311\Lib\site-packages\instructor\patch.py", line 282, in retry_sync
    return process_response(
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\18353\AppData\Local\Programs\Python\Python311\Lib\site-packages\instructor\patch.py", line 166, in process_response
    model = response_model.from_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\18353\AppData\Local\Programs\Python\Python311\Lib\site-packages\instructor\function_calls.py", line 137, in from_response
    return cls.model_validate_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\18353\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for QuestionAnswerNoEvil

```

Having a small view on the source code, but did not find answer.

Could somebody tell me what's wrong with me?

Thanks~~

**Comment by aastroza** [comment]
Could you share all the code? Particularly where you make any calls to `client.chat.completions.create`. From what I understand from your message, everything is working fine. This is the expected behavior of the validation process: if the response does not meet the criteria, you should get a validation error, and that should trigger an exception like the one shown in the output you're sharing.

**Comment by majiayu000** [comment]
Thanks for your reply. I used to think it was wrong when meeting Assertion failed. The result is correct!
