### ISSUE TITLE
Instructions in ollama.md result in a 404 error.

### ISSUE THREAD

**Issue by MattyRad** [jxnl/instructor#491]
- [x] This is an actually a bug report.
- [x] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other (ollama)

**Describe the bug**
The instructions in [ollama.md](https://github.com/jxnl/instructor/blob/main/docs/hub/ollama.md) fail with an error `openai.NotFoundError: 404 page not found`

**To Reproduce**

Confirm ollama is running.

```sh
[~] curl http://192.168.1.xxx:11434
Ollama is running
```

```sh
instructor hub pull --slug ollama --py > ollama_example.py
```

Edit `base_url` in `ollama_example.py`

```diff
17c17
<         base_url="http://localhost:11434/v1",
---
>         base_url="http://192.168.1.xxx:11434/v1",
```

```sh
Traceback (most recent call last):
  File "/home/x/ollama_example2.py", line 23, in <module>
    resp = client.chat.completions.create(
  File "/home/x/.local/lib/python3.10/site-packages/instructor/patch.py", line 575, in new_create_sync
    response = retry_sync(
  File "/home/x/.local/lib/python3.10/site-packages/instructor/patch.py", line 406, in retry_sync
    for attempt in max_retries:
  File "/home/x/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/x/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/x/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/x/.local/lib/python3.10/site-packages/instructor/patch.py", line 409, in retry_sync
    response = func(*args, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 659, in create
    return self._post(
  File "/home/x/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/x/.local/lib/python3.10/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
  File "/home/x/.local/lib/python3.10/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found
```

**Expected behavior**
There should be a successful connection to the ollama server. 

**Screenshots**
N/A

**Comment by jxnl** [comment]
does the completion run work if if you do not patch the instructor client

**Comment by MattyRad** [comment]
If I do not patch the instructor client, and simply use `base_url="http://localhost:11434/v1",`, it still does not appear to work, and fails with the same error.

The ollama server does appear to receive the request, if that helps:

```
[~] ollama serve
2024/03/06 17:52:06 images.go:799: total blobs: 9
2024/03/06 17:52:06 images.go:806: total unused blobs removed: 0
2024/03/06 17:52:06 routes.go:777: Listening on 127.0.0.1:11434 (version 0.1.10)
2024/03/06 17:52:06 routes.go:797: Warning: GPU support may not be enabled, check you have installed GPU drivers: nvidia-smi command failed
[GIN] 2024/03/06 - 17:52:17 | 200 |    1.083246ms |       127.0.0.1 | GET      "/"
[GIN] 2024/03/06 - 17:52:28 | 404 |       4.956µs |       127.0.0.1 | POST     "/v1/chat/completions"
```

The `[GIN] 2024/03/06 - 17:52:28 | 404 |       4.956µs |       127.0.0.1 | POST     "/v1/chat/completions"` line is the line which triggers upon executing `python3 ollama_example.py`.

**Comment by Vasilije1990** [comment]
I've tried the same thing. Updating the instructor to the latest version + fresh ollama installation worked for me.
