### ISSUE TITLE
'instructor' has no attribute 'patch'

### ISSUE THREAD

**Issue by Saif-Shines** [jxnl/instructor#498]
I started seeing the following `AttributeError` after recent release. It has updates to `patch`

Here is what I see:

```sh
python instructor.py
Traceback (most recent call last):
  File "/Users/saif/notebooks/python/instructor.py", line 1, in <module>
    import instructor
  File "/Users/saif/notebooks/python/instructor.py", line 15, in <module>
    client = instructor.patch(portkey)
             ^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'instructor' has no attribute 'patch' (most likely due to a circular import)
```
How do I solve this?

**Comment by jxnl** [comment]
your script is also called instructor.py you're trying to import from itself. rename it to run.py
