### ISSUE TITLE
Instructor groq example not working

### ISSUE THREAD

**Issue by rabem00** [jxnl/instructor#556]
- [x ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ x] Other : groq with mixtral

**Describe the bug**
Trying the example from instructor hub or described on https://python.useinstructor.com/hub/groq/ , but getting an error.
```
% python groq_example.py 
Traceback (most recent call last):
  File "/Users/Development/lab/structured-output/instructor/groq_example.py", line 16, in <module>
    client = instructor.from_openai(client, mode=instructor.Mode.MD_JSON)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/instructor/lib/python3.10/site-packages/instructor/client.py", line 274, in from_openai
    assert isinstance(
AssertionError: Client must be an instance of openai.OpenAI or openai.AsyncOpenAI
```

**To Reproduce**
Get the described example on https://python.useinstructor.com/hub/groq/  and run.
It seems instructor client.py is expecting openai.OpenAI  as described on line 274 of client.py, so the example will never work.

Maybe I'm missing something?

**Comment by rabem00** [comment]
I just created a pull request #561 with a possible from_groq solution.
