### ISSUE TITLE
Cohere doesn't work when response_model = None

### ISSUE THREAD

**Issue by marcasty** [jxnl/instructor#787]
- [x] This is actually a bug report.

**What Model are you using?**
- [x] command-r

**Describe the bug**
I use instructor for all types of chat operations, including unstructured, because the API integrations are so nice and easy. I get unstructured responses by passing response_model = None (it looks like this is on purpose)
This works for every client I've tried (openai, anthropic, mistral, groq) *except* cohere

**To Reproduce**

```python
from cohere import Client
from instructor import from_cohere

model_name = "command-r"
co = Client()
client = from_cohere(co, model_name=model_name, max_tokens=1000)

messages = [{"role": "user", "content": "Tell me about your day"}]

# run chat completion
response = client.messages.create(
    messages=messages,
    response_model=None,
    temperature=0
)

print(response)
```

**Expected behavior**
I expect to see the cohere response

**Screenshots**
```bash
(llm) py -m examples.error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marka\fun\any-llm\examples\error.py", line 13, in <module>
    response = client.messages.create(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\instructor\client.py", line 91, in create
    return self.create_fn(
           ^^^^^^^^^^^^^^^
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\instructor\patch.py", line 143, in new_create_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\instructor\retry.py", line 151, in retry_sync
    for attempt in max_retries:
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\tenacity\__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marka\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marka\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\instructor\retry.py", line 154, in retry_sync
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marka\fun\FoodGuru\llm\Lib\site-packages\cohere\client.py", line 33, in wrapped
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseCohere.chat() got an unexpected keyword argument 'messages'
```

**Comment by jxnl** [comment]
why use instructor when theres no response_model? standardization?

**Comment by marcasty** [comment]
> why use instructor when theres no response_model? standardization?  


You already support all of the APIs for chat 

I can define a rag pipeline with a yaml and experiment fast. Recently i learned that chain of thought is much worse in tool or json mode so I'd rather think step by step in a separate call

**Comment by nkeilar** [comment]
I'm also here looking for a way to have the model not respond with a tool/model, in the case the users request doesn't require one. I realise I could define a model with a field message or something. But as I understand it OpenAI supports letting the llm decide if a tool, a which tool should be called. I can't find a way in instructor to allow no tool and just a message to be returned.

**Comment by arnaudstiegler** [comment]
Same feedback on my end :) I'm using the Anthropic client for a bunch of tasks, and I'd like to reuse the instructor-patched Anthropic client without a response_model to streamline the implementation and avoid having 2 different clients

**Comment by ivanleomk** [comment]
@nkeilar  and @marcasty this should work with the latest version of instructor
